/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overcookedfide;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author admin
 */
public class GUIOverCooked extends javax.swing.JFrame {

    /**
     * Creates new form GUIOverCooked
     */
    private Timer tiempo;
    private int centesimas_segundos = 0;
    private int segundo = 0;
    private int minutos = 0;
    private int horas = 0;
    ColaOrden cola = new ColaOrden(this);
    ListaCircularIngredientes cinta = new ListaCircularIngredientes();
    private String ordenactual = "";

    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimas_segundos++;
            if (centesimas_segundos == 99) {
                segundo++;
                centesimas_segundos = 0;
            }
            if (segundo == 60) {
                minutos++;
                segundo = 0;
                if (cinta.size <= 3) {
                    manejarBoton();
                }
            }
            if (minutos == 5) {
                JOptionPane.showMessageDialog(null, "Juego terminado");
                minutos = 0;
                segundo = 0;
                System.exit(-1);
            }
            actualizarlblTiempo();
        }
    };

    private void manejarBoton() {
        for (int i = 1; i <= 5; i++) {
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, i));
            if (i == 1) {
                btn1.setText(ingredienteAleatorio);
            }
            if (i == 2) {
                btn2.setText(ingredienteAleatorio);
            }
            if (i == 3) {
                btn3.setText(ingredienteAleatorio);
            }
            if (i == 4) {
                btn4.setText(ingredienteAleatorio);
            }
            if (i == 5) {
                btn5.setText(ingredienteAleatorio);
            }
        }
    }

    public void actualizarBoton(int numeroBoton, String texto) {
        switch (numeroBoton) {
            case 1:
                btn1.setText("" + texto);
                break;
            case 2:
                btn2.setText("" + texto);
                break;
            case 3:
                btn3.setText("" + texto);
                break;
            case 4:
                btn4.setText("" + texto);
                break;
            case 5:
                btn5.setText("" + texto);
                break;
            default:
                break;
        }
    }

    private void actualizarlblTiempo() {
        String txtTiempo = (minutos <= 9 ? "0" : "") + minutos + ":" + (segundo <= 9 ? "0" : "") + segundo;
        lbl_tiempo.setText(txtTiempo);
    }

    public GUIOverCooked() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Proyecto");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        tiempo = new Timer(10, acciones);

    }

    public void actualizarlblingredient(String text) {
        lbl_ingredient.setText(text);
    }

    public void actualizarLabel(int numeroOrden, String texto) {
        switch (numeroOrden) {
            case 1:
                lbl_orden1.setText(texto);
                break;
            case 2:
                lbl_orden2.setText(texto);
                break;
            case 3:
                lbl_orden3.setText(texto);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        orden1 = new javax.swing.JPanel();
        lbl_orden1 = new javax.swing.JLabel();
        orden2 = new javax.swing.JPanel();
        lbl_orden2 = new javax.swing.JLabel();
        orden3 = new javax.swing.JPanel();
        lbl_orden3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_ingredient = new javax.swing.JLabel();
        lbl_ingredientfaltantes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnBasurero = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_tiempo = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingredientes");

        btn1.setText("jButton1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("jButton1");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("jButton1");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("jButton1");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("jButton1");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbl_orden1.setText("Orden1");

        javax.swing.GroupLayout orden1Layout = new javax.swing.GroupLayout(orden1);
        orden1.setLayout(orden1Layout);
        orden1Layout.setHorizontalGroup(
            orden1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orden1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_orden1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        orden1Layout.setVerticalGroup(
            orden1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orden1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_orden1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lbl_orden2.setText("Orden2");

        javax.swing.GroupLayout orden2Layout = new javax.swing.GroupLayout(orden2);
        orden2.setLayout(orden2Layout);
        orden2Layout.setHorizontalGroup(
            orden2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orden2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_orden2)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        orden2Layout.setVerticalGroup(
            orden2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orden2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_orden2)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        lbl_orden3.setText("Orden3");

        javax.swing.GroupLayout orden3Layout = new javax.swing.GroupLayout(orden3);
        orden3.setLayout(orden3Layout);
        orden3Layout.setHorizontalGroup(
            orden3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orden3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_orden3)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        orden3Layout.setVerticalGroup(
            orden3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orden3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_orden3)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ordenes");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingredientes faltantes:");

        lbl_ingredient.setText("ingrediente");

        lbl_ingredientfaltantes.setText("ingrediente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbl_ingredient, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ingredientfaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190, 190, 190))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbl_ingredientfaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbl_ingredient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tiempo");

        jLabel7.setText("Orden actual -->");

        btnBasurero.setText("Basurero");
        btnBasurero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasureroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBasurero)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBasurero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Basura");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Puntos: ");

        lbl_tiempo.setText("Tiempo");

        jButton8.setText("Iniciar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_tiempo))
                .addGap(540, 540, 540))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(orden1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(orden2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orden3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orden1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addComponent(orden2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(orden3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(btn2.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 2));
            btn2.setText(ingredienteAleatorio);
        }
        if(btn1.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 1));
            btn1.setText(ingredienteAleatorio);
        }
        if(btn4.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 4));
            btn4.setText(ingredienteAleatorio);
        }
        if(btn5.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 5));
            btn5.setText(ingredienteAleatorio);
        }
        
        if (lbl_orden1.getText().equalsIgnoreCase("clasica - puntos: 15")) {
            if (btn3.getText().equals("Pan") || btn3.getText().equals("Carne") || btn3.getText().equals("Lechuga") || btn3.getText().equals("Queso")) {
                cinta.extrae(btn3.getText());
                ordenactual += btn3.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn3.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("queso - puntos: 10")) {
            if (btn3.getText().equals("Pan") || btn3.getText().equals("Carne") || btn3.getText().equals("Queso")) {
                cinta.extrae(btn3.getText());
                ordenactual += btn3.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn3.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("carne - puntos: 5")) {
            if (btn3.getText().equals("Pan") || btn3.getText().equals("Carne")) {
                cinta.extrae(btn3.getText());
                ordenactual += btn3.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn3.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(btn1.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 1));
            btn1.setText(ingredienteAleatorio);
        }
        if(btn3.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 3));
            btn3.setText(ingredienteAleatorio);
        }
        if(btn4.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 4));
            btn4.setText(ingredienteAleatorio);
        }
        if(btn5.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 5));
            btn5.setText(ingredienteAleatorio);
        }
        
        if (lbl_orden1.getText().equalsIgnoreCase("clasica - puntos: 15")) {
            if (btn2.getText().equals("Pan") || btn2.getText().equals("Carne") || btn2.getText().equals("Lechuga") || btn2.getText().equals("Queso")) {
                cinta.extrae(btn2.getText());
                ordenactual += btn2.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn2.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("queso - puntos: 10")) {
            if (btn2.getText().equals("Pan") || btn2.getText().equals("Carne") || btn2.getText().equals("Queso")) {
                cinta.extrae(btn2.getText());
                ordenactual += btn2.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn2.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("carne - puntos: 5")) {
            if (btn2.getText().equals("Pan") || btn2.getText().equals("Carne")) {
                cinta.extrae(btn2.getText());
                ordenactual += btn2.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn2.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(btn2.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 2));
            btn2.setText(ingredienteAleatorio);
        }
        if(btn3.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 3));
            btn3.setText(ingredienteAleatorio);
        }
        if(btn1.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 1));
            btn1.setText(ingredienteAleatorio);
        }
        if(btn5.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 5));
            btn5.setText(ingredienteAleatorio);
        }
        
        if (lbl_orden1.getText().equalsIgnoreCase("clasica - puntos: 15")) {
            if (btn4.getText().equals("Pan") || btn4.getText().equals("Carne") || btn4.getText().equals("Lechuga") || btn4.getText().equals("Queso")) {
                cinta.extrae(btn4.getText());
                ordenactual += btn4.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn4.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("queso - puntos: 10")) {
            if (btn4.getText().equals("Pan") || btn4.getText().equals("Carne") || btn4.getText().equals("Queso")) {
                cinta.extrae(btn4.getText());
                ordenactual += btn4.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn4.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("carne - puntos: 5")) {
            if (btn4.getText().equals("Pan") || btn4.getText().equals("Carne")) {
                cinta.extrae(btn4.getText());
                ordenactual += btn4.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn4.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(btn2.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 2));
            btn2.setText(ingredienteAleatorio);
        }
        if(btn3.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 3));
            btn3.setText(ingredienteAleatorio);
        }
        if(btn4.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 4));
            btn4.setText(ingredienteAleatorio);
        }
        if(btn1.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 1));
            btn1.setText(ingredienteAleatorio);
        }
        
        if (lbl_orden1.getText().equalsIgnoreCase("clasica - puntos: 15")) {
            if (btn5.getText().equals("Pan") || btn5.getText().equals("Carne") || btn5.getText().equals("Lechuga") || btn5.getText().equals("Queso")) {
                cinta.extrae(btn5.getText());
                ordenactual += btn5.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn5.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();
                
                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("queso - puntos: 10")) {
            if (btn5.getText().equals("Pan") || btn5.getText().equals("Carne") || btn5.getText().equals("Queso")) {
                cinta.extrae(btn5.getText());
                ordenactual += btn5.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn5.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("carne - puntos: 5")) {
            if (btn5.getText().equals("Pan") || btn5.getText().equals("Carne")) {
                cinta.extrae(btn5.getText());
                ordenactual += btn5.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn5.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();

                btn5.setText(auxbtn4);
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
            }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        tiempo.start();
        Thread thread = new Thread(cola::llenarConOrdenesAleatorias);
        thread.start();
        Thread thread2 = new Thread(cinta::moverCinta);
        thread2.start();
        manejarBoton();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnBasureroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasureroActionPerformed
        // TODO add your handling code here:
        ListaCircularIngredientes IDesechar = new ListaCircularIngredientes();
        IDesechar.eliminarIngrediente();
        btn5.setText("");
        String auxbtn1 = btn1.getText();
        String auxbtn2 = btn2.getText();
        String auxbtn3 = btn3.getText();
        String auxbtn4 = btn4.getText();
        String auxbtn5 = btn5.getText();
        btn1.setText(auxbtn5);
        btn2.setText(auxbtn1);
        btn3.setText(auxbtn2);
        btn4.setText(auxbtn3);
        btn5.setText(auxbtn4);
        if(btn1.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 2));
            btn1.setText(ingredienteAleatorio);
        }
        if(btn2.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 2));
            btn2.setText(ingredienteAleatorio);
        }
        if(btn3.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 3));
            btn3.setText(ingredienteAleatorio);
        }
        if(btn4.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 4));
            btn4.setText(ingredienteAleatorio);
        }
        if(btn1.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 1));
            btn1.setText(ingredienteAleatorio);
        }
    }//GEN-LAST:event_btnBasureroActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(btn2.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 1));
            btn2.setText(ingredienteAleatorio);
        }
        if(btn3.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 3));
            btn3.setText(ingredienteAleatorio);
        }
        if(btn4.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 4));
            btn4.setText(ingredienteAleatorio);
        }
        if(btn5.getText().equals("")){
            String[] Ingredientes = {"Queso", "Lechuga", "Carne", "Pan"};
            Random random = new Random();
            int indiceAleatorio = random.nextInt(Ingredientes.length);
            String ingredienteAleatorio = "" + Ingredientes[indiceAleatorio];
            cinta.inserta(new Ingredient(ingredienteAleatorio, 5));
            btn5.setText(ingredienteAleatorio);
        }
        
        if (lbl_orden1.getText().equalsIgnoreCase("clasica - puntos: 15")) {
            if (btn1.getText().equals("Pan") || btn1.getText().equals("Carne") || btn1.getText().equals("Lechuga") || btn1.getText().equals("Queso")) {
                cinta.extrae(btn1.getText());
                ordenactual += btn1.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn1.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("queso - puntos: 10")) {
            if (btn1.getText().equals("Pan") || btn1.getText().equals("Carne") || btn1.getText().equals("Queso")) {
                cinta.extrae(btn1.getText());
                ordenactual += btn1.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn1.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
            }
        }
        if (lbl_orden1.getText().equalsIgnoreCase("carne - puntos: 5")) {
            if (btn1.getText().equals("Pan") || btn1.getText().equals("Carne")) {
                cinta.extrae(btn1.getText());
                ordenactual += btn1.getText();
                lbl_ingredientfaltantes.setText(ordenactual);
                btn1.setText("");
                String auxbtn1 = btn1.getText();
                String auxbtn2 = btn2.getText();
                String auxbtn3 = btn3.getText();
                String auxbtn4 = btn4.getText();
                String auxbtn5 = btn5.getText();
                btn1.setText(auxbtn5);
                btn2.setText(auxbtn1);
                btn3.setText(auxbtn2);
                btn4.setText(auxbtn3);
                btn5.setText(auxbtn4);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOverCooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOverCooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOverCooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOverCooked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOverCooked().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btnBasurero;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_ingredient;
    private javax.swing.JLabel lbl_ingredientfaltantes;
    private javax.swing.JLabel lbl_orden1;
    private javax.swing.JLabel lbl_orden2;
    private javax.swing.JLabel lbl_orden3;
    private javax.swing.JLabel lbl_tiempo;
    private javax.swing.JPanel orden1;
    private javax.swing.JPanel orden2;
    private javax.swing.JPanel orden3;
    // End of variables declaration//GEN-END:variables
}
